### PR TITLE
Chore/polish test chain

### LINKED ISSUE #75: Polish test-chain
Refactor and add README

### PR DESCRIPTION
**Pull request by honestbonsai**
Resolves #75

### CODE REVIEW

**Comment by adrianmcli** [comment]
@honestbonsai Actually, can we also add the ability to pass through Ganache options? Some tests depend on setting a mnemonic or a specific port for the Ganache provider.

**Comment by honestbonsai** [comment]
@adrianmcli Yea sure, I'll add that in.

**Comment by adrianmcli** [comment]
Looks like tests are failing because of this bug: https://stackoverflow.com/questions/55059748/travis-jest-typeerror-cannot-assign-to-read-only-property-symbolsymbol-tostr

**Comment by adrianmcli** [comment]
Apparently it's already fixed in a newer version of Jest: https://github.com/facebook/create-react-app/issues/6591#issuecomment-470900141

**Comment by honestbonsai** [comment]
Upgrading jest has fixed the tests on Travis. Merging.

**Pull request merged**
