### PR TITLE
Recreate test-app from new unbox for Contract-Call-Stream

### PR DESCRIPTION
**Pull request by adrianmcli**
The test app for `contract-call-stream` wasn't working for whatever reason, I have re-done it from scratch and it seems to work now.

For some reason, `yarn` doesn't seem to work for this test-app. You need to do `npm install` and it should work.

### CODE REVIEW

**Comment by honestbonsai** [comment]
Can you put that we should use `npm install` in the README or something? And indicate that yarn (for whatever reason) breaks it?

**Comment by adrianmcli** [comment]
Which README? The one for the whole monorepo or for these specific packages? I have a feeling that this is a problem due to Ganache-Core.

**Comment by honestbonsai** [comment]
@adrianmcli If you suspect this issue is going to be for the entire `drizzle-utils`, put it in the whole monorepo `README`

**Comment by adrianmcli** [comment]
@honestbonsai done.

**Comment by honestbonsai** [comment]
LGTM

**Pull request merged**
